services:
  - type: web
    name: emart-backend
    env: python
    runtime: python-3.11
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:application --bind 0.0.0.0:$PORT --workers 1 --max-requests 1000 --timeout 30 --keep-alive 2 --max-requests-jitter 50"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false