# Generated by Django 4.2.7 on 2025-07-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_compare"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="actual_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="exchange_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="exchange_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_text",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
