# Generated by Django 4.2.7 on 2025-07-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_offers"),
        ("store", "0004_product_actual_price_product_discount_percentage_and_more"),
    ]

    operations = []
