# Generated by Django 4.2.7 on 2025-07-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_searchquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="auto_apply",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offer",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="max_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="max_uses_per_user",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="min_order_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="offer",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("buy_one_get_one", "Buy 1 Get 1 Free"),
                    ("percentage_discount", "Percentage Discount"),
                    ("fixed_discount", "Fixed Amount Discount"),
                    ("buy_x_get_y", "Buy X Get Y Free"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="offers", to="store.product"
            ),
        ),
    ]
