# Generated by Django 4.2.7 on 2025-07-11 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_offer_auto_apply_offer_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="min_quantity",
            new_name="buy_quantity",
        ),
        migrations.RenameField(
            model_name="offer",
            old_name="discount_value",
            new_name="combo_price",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="max_quantity",
        ),
        migrations.AddField(
            model_name="offer",
            name="badge_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="offer",
            name="code",
            field=models.CharField(default="OFFER001", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="combo_products",
            field=models.ManyToManyField(
                blank=True, related_name="combo_offers", to="store.product"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="offer",
            name="first_time_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offer",
            name="flat_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="offer",
            name="free_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="free_offers",
                to="store.product",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="get_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="offer",
            name="max_discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("discount", "Percentage Discount"),
                    ("flat", "Flat ₹ Off"),
                    ("bogo", "Buy 1 Get 1 Free"),
                    ("buy_x_get_y", "Buy X Get Y Free"),
                    ("combo", "Combo Offer"),
                    ("category_offer", "Category Offer"),
                    ("first_time", "First Purchase Offer"),
                ],
                max_length=20,
            ),
        ),
    ]
