# Generated by Django 4.2.7 on 2025-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
