# Generated by Django 4.2.7 on 2025-07-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_offer_offer_type"),
    ]

    operations = []
