# Generated by Django 4.2.7 on 2025-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_merge_20250723_2329"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
