# Generated by Django 4.2.7 on 2025-07-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_product_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_file",
            field=models.TextField(blank=True, null=True),
        ),
    ]
