# Generated by Django 4.2.7 on 2025-07-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_product_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Cash on Delivery", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
