# Generated by Django 4.2.7 on 2025-07-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_combo_offers"),
        ("store", "0016_order_payment_details_order_payment_method_and_more"),
    ]

    operations = []
