# Generated by Django 4.2.7 on 2025-07-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_merge_20250725_2048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("discount", "Percentage Discount"),
                    ("flat", "Flat ₹ Off"),
                    ("category_offer", "Category Offer"),
                    ("first_time", "First Purchase Offer"),
                ],
                max_length=20,
            ),
        ),
    ]
